<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-06-11">

<title>Cirrhosis parametric survival model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="cirrhosis_files/libs/clipboard/clipboard.min.js"></script>
<script src="cirrhosis_files/libs/quarto-html/quarto.js"></script>
<script src="cirrhosis_files/libs/quarto-html/popper.min.js"></script>
<script src="cirrhosis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="cirrhosis_files/libs/quarto-html/anchor.min.js"></script>
<link href="cirrhosis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="cirrhosis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="cirrhosis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="cirrhosis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="cirrhosis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Cirrhosis parametric survival model</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 11, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="about-data" class="level1">
<h1>About data</h1>
<p>The data provided is sourced from a Mayo Clinic study on the randomised controlled trial for the drug D-penicillamine for primary biliary cirrhosis (PBC) of the liver carried out from 1974 to 1984. 312 patients took part in the study, 112 patients did not join the trial but agreed to record basic metrics and survival tracking but 6 of them soon went untraceable, leaving 102 of them. The dataset encompasses information on 418 patients followed over a period denoted by N_Days. This timeframe tracks the duration from patient registration until either death, liver transplantation, or the study’s conclusion (July 1986). It incorporates the data on patients’ sociodemographic characteristics, medical history, clinical signs, disease severity and outcome. There was 17 clinical features available for predicting survival state of patients with liver cirrhosis. The survival states include 0 = D (death), 1 = C (censored), 2 = CL (censored due to liver transplantation).</p>
</section>
<section id="data-analysis" class="level1">
<h1>Data Analysis</h1>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory data analysis</h2>
<section id="load-environment" class="level3">
<h3 class="anchored" data-anchor-id="load-environment">Load environment</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(flexsurv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: survival</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survminer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggpubr

Attaching package: 'survminer'

The following object is masked from 'package:survival':

    myeloma</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>data0 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'cirrhosis.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="explore-data" class="level3">
<h3 class="anchored" data-anchor-id="explore-data">Explore Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       ID            N_Days        Status              Drug          
 Min.   :  1.0   Min.   :  41   Length:418         Length:418        
 1st Qu.:105.2   1st Qu.:1093   Class :character   Class :character  
 Median :209.5   Median :1730   Mode  :character   Mode  :character  
 Mean   :209.5   Mean   :1918                                        
 3rd Qu.:313.8   3rd Qu.:2614                                        
 Max.   :418.0   Max.   :4795                                        
                                                                     
      Age            Sex              Ascites          Hepatomegaly      
 Min.   : 9598   Length:418         Length:418         Length:418        
 1st Qu.:15644   Class :character   Class :character   Class :character  
 Median :18628   Mode  :character   Mode  :character   Mode  :character  
 Mean   :18533                                                           
 3rd Qu.:21273                                                           
 Max.   :28650                                                           
                                                                         
   Spiders             Edema             Bilirubin       Cholesterol    
 Length:418         Length:418         Min.   : 0.300   Min.   : 120.0  
 Class :character   Class :character   1st Qu.: 0.800   1st Qu.: 249.5  
 Mode  :character   Mode  :character   Median : 1.400   Median : 309.5  
                                       Mean   : 3.221   Mean   : 369.5  
                                       3rd Qu.: 3.400   3rd Qu.: 400.0  
                                       Max.   :28.000   Max.   :1775.0  
                                                        NA's   :134     
    Albumin          Copper          Alk_Phos            SGOT       
 Min.   :1.960   Min.   :  4.00   Min.   :  289.0   Min.   : 26.35  
 1st Qu.:3.243   1st Qu.: 41.25   1st Qu.:  871.5   1st Qu.: 80.60  
 Median :3.530   Median : 73.00   Median : 1259.0   Median :114.70  
 Mean   :3.497   Mean   : 97.65   Mean   : 1982.7   Mean   :122.56  
 3rd Qu.:3.770   3rd Qu.:123.00   3rd Qu.: 1980.0   3rd Qu.:151.90  
 Max.   :4.640   Max.   :588.00   Max.   :13862.4   Max.   :457.25  
                 NA's   :108      NA's   :106       NA's   :106     
 Tryglicerides      Platelets      Prothrombin        Stage      
 Min.   : 33.00   Min.   : 62.0   Min.   : 9.00   Min.   :1.000  
 1st Qu.: 84.25   1st Qu.:188.5   1st Qu.:10.00   1st Qu.:2.000  
 Median :108.00   Median :251.0   Median :10.60   Median :3.000  
 Mean   :124.70   Mean   :257.0   Mean   :10.73   Mean   :3.024  
 3rd Qu.:151.00   3rd Qu.:318.0   3rd Qu.:11.10   3rd Qu.:4.000  
 Max.   :598.00   Max.   :721.0   Max.   :18.00   Max.   :4.000  
 NA's   :136      NA's   :11      NA's   :2       NA's   :6      </code></pre>
</div>
</div>
</section>
<section id="data-wrangling" class="level3">
<h3 class="anchored" data-anchor-id="data-wrangling">Data wrangling</h3>
<p>set outcome “N_days” as numeric data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>data1 <span class="ot">&lt;-</span> data0 <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">N_Days =</span> <span class="fu">as.numeric</span>(N_Days))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Clean and prepare data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>data1 <span class="ot">&lt;-</span> data1 <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">status_binary =</span> <span class="fu">recode</span>(Status, <span class="st">"D"</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">"C"</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">"CL"</span> <span class="ot">=</span> <span class="dv">0</span>),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">status_binary =</span> <span class="fu">factor</span>(status_binary, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"censored"</span>, <span class="st">"death"</span>)),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sex =</span> <span class="fu">recode</span>(Sex, <span class="st">"F"</span> <span class="ot">=</span> <span class="st">"Female"</span>, <span class="st">"M"</span> <span class="ot">=</span> <span class="st">"Male"</span>),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sex =</span> <span class="fu">as.factor</span>(Sex),  <span class="co"># Ensure sex is a factor</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Bilirubin =</span> <span class="fu">as.numeric</span>(Bilirubin),  <span class="co"># Ensure Bilirubin is numeric</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">time =</span> <span class="fu">as.numeric</span>(N_Days),  <span class="co"># Use N_days (now numeric) for survival analysis</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_years =</span> <span class="fu">as.numeric</span>(<span class="fu">duration</span>(Age, <span class="at">units =</span> <span class="st">"days"</span>) <span class="sc">/</span> <span class="fu">dyears</span>(<span class="dv">1</span>)),  <span class="co"># Convert age in days to age in years using lubridate</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Stage =</span> <span class="fu">as.factor</span>(Stage)  <span class="co"># Ensure Stage is a factor</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character), <span class="sc">~</span> <span class="fu">recode</span>(., <span class="st">"N"</span> <span class="ot">=</span> <span class="st">"No"</span>, <span class="st">"Y"</span> <span class="ot">=</span> <span class="st">"Yes"</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.integer, as.numeric) <span class="sc">%&gt;%</span>  <span class="co"># Convert all integer columns to numeric</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.character, as.factor) <span class="sc">%&gt;%</span>  <span class="co"># Convert all character columns to factors</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(time), <span class="sc">!</span><span class="fu">is.na</span>(Bilirubin), <span class="sc">!</span><span class="fu">is.na</span>(Sex), <span class="sc">!</span><span class="fu">is.na</span>(age_years), <span class="sc">!</span><span class="fu">is.na</span>(Stage))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   412 obs. of  23 variables:
 $ ID           : num  1 2 3 4 5 6 7 8 9 10 ...
 $ N_Days       : num  400 4500 1012 1925 1504 ...
 $ Status       : Factor w/ 3 levels "C","CL","D": 3 1 3 3 2 3 1 3 3 3 ...
 $ Drug         : Factor w/ 2 levels "D-penicillamine",..: 1 1 1 1 2 2 2 2 1 2 ...
 $ Age          : num  21464 20617 25594 19994 13918 ...
 $ Sex          : Factor w/ 2 levels "Female","Male": 1 1 2 1 1 1 1 1 1 1 ...
 $ Ascites      : Factor w/ 2 levels "No","Yes": 2 1 1 1 1 1 1 1 1 2 ...
 $ Hepatomegaly : Factor w/ 2 levels "No","Yes": 2 2 1 2 2 2 2 1 1 1 ...
 $ Spiders      : Factor w/ 2 levels "No","Yes": 2 2 1 2 2 1 1 1 2 2 ...
 $ Edema        : Factor w/ 3 levels "No","S","Yes": 3 1 2 2 1 1 1 1 1 3 ...
 $ Bilirubin    : num  14.5 1.1 1.4 1.8 3.4 0.8 1 0.3 3.2 12.6 ...
 $ Cholesterol  : num  261 302 176 244 279 248 322 280 562 200 ...
 $ Albumin      : num  2.6 4.14 3.48 2.54 3.53 3.98 4.09 4 3.08 2.74 ...
 $ Copper       : num  156 54 210 64 143 50 52 52 79 140 ...
 $ Alk_Phos     : num  1718 7395 516 6122 671 ...
 $ SGOT         : num  137.9 113.5 96.1 60.6 113.2 ...
 $ Tryglicerides: num  172 88 55 92 72 63 213 189 88 143 ...
 $ Platelets    : num  190 221 151 183 136 NA 204 373 251 302 ...
 $ Prothrombin  : num  12.2 10.6 12 10.3 10.9 11 9.7 11 11 11.5 ...
 $ Stage        : Factor w/ 4 levels "1","2","3","4": 4 3 4 4 3 3 3 3 2 4 ...
 $ status_binary: Factor w/ 2 levels "censored","death": 2 1 2 2 1 2 1 2 2 2 ...
 $ time         : num  400 4500 1012 1925 1504 ...
 $ age_years    : num  58.8 56.4 70.1 54.7 38.1 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       ID            N_Days     Status                Drug          Age       
 Min.   :  1.0   Min.   :  41   C :230   D-penicillamine:158   Min.   : 9598  
 1st Qu.:103.8   1st Qu.:1094   CL: 25   Placebo        :154   1st Qu.:15609  
 Median :206.5   Median :1714   D :157   NA's           :100   Median :18628  
 Mean   :207.8   Mean   :1917                                  Mean   :18498  
 3rd Qu.:309.2   3rd Qu.:2610                                  3rd Qu.:21201  
 Max.   :418.0   Max.   :4795                                  Max.   :28650  
                                                                              
     Sex      Ascites    Hepatomegaly Spiders    Edema       Bilirubin     
 Female:368   No  :288   No  :152     No  :222   No :348   Min.   : 0.300  
 Male  : 44   Yes : 24   Yes :160     Yes : 90   S  : 44   1st Qu.: 0.800  
              NA's:100   NA's:100     NA's:100   Yes: 20   Median : 1.400  
                                                           Mean   : 3.228  
                                                           3rd Qu.: 3.400  
                                                           Max.   :28.000  
                                                                           
  Cholesterol        Albumin          Copper          Alk_Phos      
 Min.   : 120.0   Min.   :1.960   Min.   :  4.00   Min.   :  289.0  
 1st Qu.: 249.5   1st Qu.:3.248   1st Qu.: 41.25   1st Qu.:  871.5  
 Median : 309.5   Median :3.530   Median : 73.00   Median : 1259.0  
 Mean   : 369.5   Mean   :3.500   Mean   : 97.65   Mean   : 1982.7  
 3rd Qu.: 400.0   3rd Qu.:3.783   3rd Qu.:123.00   3rd Qu.: 1980.0  
 Max.   :1775.0   Max.   :4.640   Max.   :588.00   Max.   :13862.4  
 NA's   :128                      NA's   :102      NA's   :100      
      SGOT        Tryglicerides      Platelets      Prothrombin    Stage  
 Min.   : 26.35   Min.   : 33.00   Min.   : 62.0   Min.   : 9.00   1: 21  
 1st Qu.: 80.60   1st Qu.: 84.25   1st Qu.:189.0   1st Qu.:10.00   2: 92  
 Median :114.70   Median :108.00   Median :249.0   Median :10.60   3:155  
 Mean   :122.56   Mean   :124.70   Mean   :256.1   Mean   :10.73   4:144  
 3rd Qu.:151.90   3rd Qu.:151.00   3rd Qu.:318.0   3rd Qu.:11.10          
 Max.   :457.25   Max.   :598.00   Max.   :563.0   Max.   :18.00          
 NA's   :100      NA's   :130      NA's   :11      NA's   :2              
  status_binary      time        age_years    
 censored:255   Min.   :  41   Min.   :26.28  
 death   :157   1st Qu.:1094   1st Qu.:42.74  
                Median :1714   Median :51.00  
                Mean   :1917   Mean   :50.65  
                3rd Qu.:2610   3rd Qu.:58.04  
                Max.   :4795   Max.   :78.44  
                                              </code></pre>
</div>
</div>
</section>
<section id="describe-data" class="level3">
<h3 class="anchored" data-anchor-id="describe-data">Describe data</h3>
<p>overall summary table</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>summary_overall <span class="ot">&lt;-</span> data1 <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>ID, <span class="sc">-</span>Status, <span class="sc">-</span>Age) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tbl_summary</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> status_binary,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> <span class="fu">list</span>(<span class="fu">all_continuous</span>() <span class="sc">~</span> <span class="st">"{mean} ({sd})"</span>),</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>     ) <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">add_overall</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">add_p</span>()</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>summary_overall</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div id="bpoomjohfl" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#bpoomjohfl table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#bpoomjohfl thead, #bpoomjohfl tbody, #bpoomjohfl tfoot, #bpoomjohfl tr, #bpoomjohfl td, #bpoomjohfl th {
  border-style: none;
}

#bpoomjohfl p {
  margin: 0;
  padding: 0;
}

#bpoomjohfl .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#bpoomjohfl .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#bpoomjohfl .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#bpoomjohfl .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#bpoomjohfl .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bpoomjohfl .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bpoomjohfl .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bpoomjohfl .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#bpoomjohfl .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#bpoomjohfl .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#bpoomjohfl .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#bpoomjohfl .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#bpoomjohfl .gt_spanner_row {
  border-bottom-style: hidden;
}

#bpoomjohfl .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#bpoomjohfl .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#bpoomjohfl .gt_from_md > :first-child {
  margin-top: 0;
}

#bpoomjohfl .gt_from_md > :last-child {
  margin-bottom: 0;
}

#bpoomjohfl .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#bpoomjohfl .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#bpoomjohfl .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#bpoomjohfl .gt_row_group_first td {
  border-top-width: 2px;
}

#bpoomjohfl .gt_row_group_first th {
  border-top-width: 2px;
}

#bpoomjohfl .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bpoomjohfl .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#bpoomjohfl .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#bpoomjohfl .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bpoomjohfl .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bpoomjohfl .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#bpoomjohfl .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#bpoomjohfl .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#bpoomjohfl .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bpoomjohfl .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bpoomjohfl .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#bpoomjohfl .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bpoomjohfl .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#bpoomjohfl .gt_left {
  text-align: left;
}

#bpoomjohfl .gt_center {
  text-align: center;
}

#bpoomjohfl .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#bpoomjohfl .gt_font_normal {
  font-weight: normal;
}

#bpoomjohfl .gt_font_bold {
  font-weight: bold;
}

#bpoomjohfl .gt_font_italic {
  font-style: italic;
}

#bpoomjohfl .gt_super {
  font-size: 65%;
}

#bpoomjohfl .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#bpoomjohfl .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#bpoomjohfl .gt_indent_1 {
  text-indent: 5px;
}

#bpoomjohfl .gt_indent_2 {
  text-indent: 10px;
}

#bpoomjohfl .gt_indent_3 {
  text-indent: 15px;
}

#bpoomjohfl .gt_indent_4 {
  text-indent: 20px;
}

#bpoomjohfl .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="<strong>Characteristic</strong>"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>Overall</strong>, N = 412<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>Overall</strong>, N = 412<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>censored</strong>, N = 255<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>censored</strong>, N = 255<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>death</strong>, N = 157<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>death</strong>, N = 157<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>p-value</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>2</sup></span>"><strong>p-value</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>2</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">N_Days</td>
<td headers="stat_0" class="gt_row gt_center">1,917 (1,100)</td>
<td headers="stat_1" class="gt_row gt_center">2,246 (997)</td>
<td headers="stat_2" class="gt_row gt_center">1,381 (1,051)</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Drug</td>
<td headers="stat_0" class="gt_row gt_center"><br></td>
<td headers="stat_1" class="gt_row gt_center"><br></td>
<td headers="stat_2" class="gt_row gt_center"><br></td>
<td headers="p.value" class="gt_row gt_center">0.7</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;D-penicillamine</td>
<td headers="stat_0" class="gt_row gt_center">158 (51%)</td>
<td headers="stat_1" class="gt_row gt_center">93 (50%)</td>
<td headers="stat_2" class="gt_row gt_center">65 (52%)</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Placebo</td>
<td headers="stat_0" class="gt_row gt_center">154 (49%)</td>
<td headers="stat_1" class="gt_row gt_center">94 (50%)</td>
<td headers="stat_2" class="gt_row gt_center">60 (48%)</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td headers="stat_0" class="gt_row gt_center">100</td>
<td headers="stat_1" class="gt_row gt_center">68</td>
<td headers="stat_2" class="gt_row gt_center">32</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">Sex</td>
<td headers="stat_0" class="gt_row gt_center"><br></td>
<td headers="stat_1" class="gt_row gt_center"><br></td>
<td headers="stat_2" class="gt_row gt_center"><br></td>
<td headers="p.value" class="gt_row gt_center">0.018</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Female</td>
<td headers="stat_0" class="gt_row gt_center">368 (89%)</td>
<td headers="stat_1" class="gt_row gt_center">235 (92%)</td>
<td headers="stat_2" class="gt_row gt_center">133 (85%)</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Male</td>
<td headers="stat_0" class="gt_row gt_center">44 (11%)</td>
<td headers="stat_1" class="gt_row gt_center">20 (7.8%)</td>
<td headers="stat_2" class="gt_row gt_center">24 (15%)</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">Ascites</td>
<td headers="stat_0" class="gt_row gt_center">24 (7.7%)</td>
<td headers="stat_1" class="gt_row gt_center">1 (0.5%)</td>
<td headers="stat_2" class="gt_row gt_center">23 (18%)</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td headers="stat_0" class="gt_row gt_center">100</td>
<td headers="stat_1" class="gt_row gt_center">68</td>
<td headers="stat_2" class="gt_row gt_center">32</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">Hepatomegaly</td>
<td headers="stat_0" class="gt_row gt_center">160 (51%)</td>
<td headers="stat_1" class="gt_row gt_center">72 (39%)</td>
<td headers="stat_2" class="gt_row gt_center">88 (70%)</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td headers="stat_0" class="gt_row gt_center">100</td>
<td headers="stat_1" class="gt_row gt_center">68</td>
<td headers="stat_2" class="gt_row gt_center">32</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">Spiders</td>
<td headers="stat_0" class="gt_row gt_center">90 (29%)</td>
<td headers="stat_1" class="gt_row gt_center">38 (20%)</td>
<td headers="stat_2" class="gt_row gt_center">52 (42%)</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td headers="stat_0" class="gt_row gt_center">100</td>
<td headers="stat_1" class="gt_row gt_center">68</td>
<td headers="stat_2" class="gt_row gt_center">32</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">Edema</td>
<td headers="stat_0" class="gt_row gt_center"><br></td>
<td headers="stat_1" class="gt_row gt_center"><br></td>
<td headers="stat_2" class="gt_row gt_center"><br></td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;No</td>
<td headers="stat_0" class="gt_row gt_center">348 (84%)</td>
<td headers="stat_1" class="gt_row gt_center">236 (93%)</td>
<td headers="stat_2" class="gt_row gt_center">112 (71%)</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;S</td>
<td headers="stat_0" class="gt_row gt_center">44 (11%)</td>
<td headers="stat_1" class="gt_row gt_center">18 (7.1%)</td>
<td headers="stat_2" class="gt_row gt_center">26 (17%)</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Yes</td>
<td headers="stat_0" class="gt_row gt_center">20 (4.9%)</td>
<td headers="stat_1" class="gt_row gt_center">1 (0.4%)</td>
<td headers="stat_2" class="gt_row gt_center">19 (12%)</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">Bilirubin</td>
<td headers="stat_0" class="gt_row gt_center">3.2 (4.4)</td>
<td headers="stat_1" class="gt_row gt_center">1.8 (2.2)</td>
<td headers="stat_2" class="gt_row gt_center">5.6 (5.9)</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Cholesterol</td>
<td headers="stat_0" class="gt_row gt_center">370 (232)</td>
<td headers="stat_1" class="gt_row gt_center">339 (193)</td>
<td headers="stat_2" class="gt_row gt_center">416 (275)</td>
<td headers="p.value" class="gt_row gt_center">0.013</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td headers="stat_0" class="gt_row gt_center">128</td>
<td headers="stat_1" class="gt_row gt_center">85</td>
<td headers="stat_2" class="gt_row gt_center">43</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">Albumin</td>
<td headers="stat_0" class="gt_row gt_center">3.50 (0.42)</td>
<td headers="stat_1" class="gt_row gt_center">3.59 (0.37)</td>
<td headers="stat_2" class="gt_row gt_center">3.36 (0.47)</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Copper</td>
<td headers="stat_0" class="gt_row gt_center">98 (86)</td>
<td headers="stat_1" class="gt_row gt_center">72 (65)</td>
<td headers="stat_2" class="gt_row gt_center">135 (98)</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td headers="stat_0" class="gt_row gt_center">102</td>
<td headers="stat_1" class="gt_row gt_center">69</td>
<td headers="stat_2" class="gt_row gt_center">33</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">Alk_Phos</td>
<td headers="stat_0" class="gt_row gt_center">1,983 (2,140)</td>
<td headers="stat_1" class="gt_row gt_center">1,574 (1,569)</td>
<td headers="stat_2" class="gt_row gt_center">2,594 (2,677)</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td headers="stat_0" class="gt_row gt_center">100</td>
<td headers="stat_1" class="gt_row gt_center">68</td>
<td headers="stat_2" class="gt_row gt_center">32</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">SGOT</td>
<td headers="stat_0" class="gt_row gt_center">123 (57)</td>
<td headers="stat_1" class="gt_row gt_center">110 (52)</td>
<td headers="stat_2" class="gt_row gt_center">142 (58)</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td headers="stat_0" class="gt_row gt_center">100</td>
<td headers="stat_1" class="gt_row gt_center">68</td>
<td headers="stat_2" class="gt_row gt_center">32</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">Tryglicerides</td>
<td headers="stat_0" class="gt_row gt_center">125 (65)</td>
<td headers="stat_1" class="gt_row gt_center">114 (51)</td>
<td headers="stat_2" class="gt_row gt_center">140 (79)</td>
<td headers="p.value" class="gt_row gt_center">0.003</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td headers="stat_0" class="gt_row gt_center">130</td>
<td headers="stat_1" class="gt_row gt_center">86</td>
<td headers="stat_2" class="gt_row gt_center">44</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">Platelets</td>
<td headers="stat_0" class="gt_row gt_center">256 (96)</td>
<td headers="stat_1" class="gt_row gt_center">265 (91)</td>
<td headers="stat_2" class="gt_row gt_center">241 (101)</td>
<td headers="p.value" class="gt_row gt_center">0.004</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td headers="stat_0" class="gt_row gt_center">11</td>
<td headers="stat_1" class="gt_row gt_center">5</td>
<td headers="stat_2" class="gt_row gt_center">6</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">Prothrombin</td>
<td headers="stat_0" class="gt_row gt_center">10.73 (1.03)</td>
<td headers="stat_1" class="gt_row gt_center">10.44 (0.90)</td>
<td headers="stat_2" class="gt_row gt_center">11.20 (1.05)</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;Unknown</td>
<td headers="stat_0" class="gt_row gt_center">2</td>
<td headers="stat_1" class="gt_row gt_center">1</td>
<td headers="stat_2" class="gt_row gt_center">1</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">Stage</td>
<td headers="stat_0" class="gt_row gt_center"><br></td>
<td headers="stat_1" class="gt_row gt_center"><br></td>
<td headers="stat_2" class="gt_row gt_center"><br></td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;1</td>
<td headers="stat_0" class="gt_row gt_center">21 (5.1%)</td>
<td headers="stat_1" class="gt_row gt_center">19 (7.5%)</td>
<td headers="stat_2" class="gt_row gt_center">2 (1.3%)</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;2</td>
<td headers="stat_0" class="gt_row gt_center">92 (22%)</td>
<td headers="stat_1" class="gt_row gt_center">69 (27%)</td>
<td headers="stat_2" class="gt_row gt_center">23 (15%)</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;3</td>
<td headers="stat_0" class="gt_row gt_center">155 (38%)</td>
<td headers="stat_1" class="gt_row gt_center">107 (42%)</td>
<td headers="stat_2" class="gt_row gt_center">48 (31%)</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;4</td>
<td headers="stat_0" class="gt_row gt_center">144 (35%)</td>
<td headers="stat_1" class="gt_row gt_center">60 (24%)</td>
<td headers="stat_2" class="gt_row gt_center">84 (54%)</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">time</td>
<td headers="stat_0" class="gt_row gt_center">1,917 (1,100)</td>
<td headers="stat_1" class="gt_row gt_center">2,246 (997)</td>
<td headers="stat_2" class="gt_row gt_center">1,381 (1,051)</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">age_years</td>
<td headers="stat_0" class="gt_row gt_center">51 (10)</td>
<td headers="stat_1" class="gt_row gt_center">49 (10)</td>
<td headers="stat_2" class="gt_row gt_center">54 (10)</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="5"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> Mean (SD); n (%)</td>
    </tr>
    <tr>
      <td class="gt_footnote" colspan="5"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>2</sup></span> Wilcoxon rank sum test; Pearson’s Chi-squared test</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
</div>
</section>
</section>
<section id="kaplan-meir-survival-estimates" class="level2">
<h2 class="anchored" data-anchor-id="kaplan-meir-survival-estimates"><strong>Kaplan-Meir Survival estimates</strong></h2>
<section id="kaplan-meier-estimates-for-overall" class="level3">
<h3 class="anchored" data-anchor-id="kaplan-meier-estimates-for-overall"><strong>Kaplan-Meier estimates for overall</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>KM1 <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(<span class="at">time =</span> data1<span class="sc">$</span>time, <span class="at">event =</span> data1<span class="sc">$</span>status_binary <span class="sc">==</span> <span class="st">"death"</span>) <span class="sc">~</span> <span class="dv">1</span>, </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">type =</span> <span class="st">"kaplan-meier"</span>, <span class="at">data =</span> data1)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(KM1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(time = data1$time, event = data1$status_binary == 
    "death") ~ 1, data = data1, type = "kaplan-meier")

 time n.risk n.event survival std.err lower 95% CI upper 95% CI
   41    412       1    0.998 0.00242        0.993        1.000
   43    411       1    0.995 0.00342        0.988        1.000
   51    410       1    0.993 0.00419        0.985        1.000
   71    409       1    0.990 0.00483        0.981        1.000
   77    408       1    0.988 0.00539        0.977        0.998
   94    407       1    0.985 0.00590        0.974        0.997
  110    406       1    0.983 0.00637        0.971        0.996
  111    405       1    0.981 0.00680        0.967        0.994
  130    404       1    0.978 0.00720        0.964        0.992
  131    403       1    0.976 0.00758        0.961        0.991
  140    402       1    0.973 0.00794        0.958        0.989
  179    401       1    0.971 0.00828        0.955        0.987
  186    400       1    0.968 0.00861        0.952        0.985
  191    399       1    0.966 0.00893        0.949        0.984
  193    398       1    0.964 0.00923        0.946        0.982
  198    397       1    0.961 0.00952        0.943        0.980
  207    396       1    0.959 0.00980        0.940        0.978
  216    395       1    0.956 0.01007        0.937        0.976
  221    394       1    0.954 0.01033        0.934        0.974
  223    393       1    0.951 0.01059        0.931        0.972
  249    392       1    0.949 0.01084        0.928        0.971
  264    391       2    0.944 0.01131        0.922        0.967
  304    389       1    0.942 0.01154        0.919        0.965
  321    388       1    0.939 0.01176        0.917        0.963
  326    387       1    0.937 0.01198        0.914        0.961
  334    386       1    0.934 0.01219        0.911        0.959
  348    385       1    0.932 0.01240        0.908        0.957
  359    384       1    0.930 0.01260        0.905        0.955
  388    383       1    0.927 0.01280        0.902        0.953
  400    382       1    0.925 0.01300        0.900        0.951
  460    381       1    0.922 0.01319        0.897        0.949
  489    380       1    0.920 0.01337        0.894        0.946
  515    379       1    0.917 0.01356        0.891        0.944
  549    377       1    0.915 0.01374        0.889        0.942
  552    376       1    0.913 0.01391        0.886        0.940
  559    375       1    0.910 0.01409        0.883        0.938
  597    374       2    0.905 0.01443        0.877        0.934
  611    372       1    0.903 0.01459        0.875        0.932
  625    370       1    0.900 0.01476        0.872        0.930
  662    369       1    0.898 0.01492        0.869        0.928
  673    368       1    0.896 0.01507        0.866        0.926
  681    367       1    0.893 0.01523        0.864        0.923
  694    365       1    0.891 0.01538        0.861        0.921
  703    364       1    0.888 0.01553        0.858        0.919
  708    363       1    0.886 0.01568        0.856        0.917
  727    362       1    0.883 0.01583        0.853        0.915
  733    360       1    0.881 0.01597        0.850        0.913
  750    358       1    0.878 0.01612        0.847        0.911
  762    357       1    0.876 0.01626        0.845        0.908
  769    356       1    0.873 0.01640        0.842        0.906
  778    355       1    0.871 0.01654        0.839        0.904
  785    354       1    0.869 0.01667        0.837        0.902
  786    353       1    0.866 0.01680        0.834        0.900
  790    351       1    0.864 0.01694        0.831        0.897
  791    350       1    0.861 0.01707        0.828        0.895
  797    349       1    0.859 0.01720        0.826        0.893
  799    348       1    0.856 0.01732        0.823        0.891
  824    347       1    0.854 0.01745        0.820        0.889
  850    344       1    0.851 0.01757        0.818        0.886
  853    343       1    0.849 0.01770        0.815        0.884
  859    342       1    0.846 0.01782        0.812        0.882
  890    340       1    0.844 0.01794        0.809        0.880
  904    338       1    0.841 0.01806        0.807        0.877
  930    337       1    0.839 0.01818        0.804        0.875
  935    336       1    0.836 0.01829        0.801        0.873
  943    334       1    0.834 0.01841        0.799        0.871
  971    332       1    0.831 0.01852        0.796        0.868
  974    331       1    0.829 0.01864        0.793        0.866
  980    329       1    0.826 0.01875        0.790        0.864
  990    327       1    0.824 0.01886        0.788        0.862
  999    325       1    0.821 0.01897        0.785        0.859
 1000    324       1    0.819 0.01908        0.782        0.857
 1012    323       1    0.816 0.01919        0.779        0.855
 1037    320       1    0.814 0.01930        0.777        0.852
 1077    315       1    0.811 0.01941        0.774        0.850
 1080    314       1    0.808 0.01952        0.771        0.848
 1083    313       1    0.806 0.01963        0.768        0.845
 1095    309       1    0.803 0.01974        0.765        0.843
 1152    301       1    0.801 0.01985        0.763        0.840
 1165    299       1    0.798 0.01996        0.760        0.838
 1168    298       1    0.795 0.02008        0.757        0.836
 1170    297       1    0.793 0.02019        0.754        0.833
 1191    295       2    0.787 0.02040        0.748        0.828
 1197    293       1    0.785 0.02051        0.745        0.826
 1212    292       1    0.782 0.02062        0.742        0.823
 1217    289       1    0.779 0.02072        0.740        0.821
 1235    285       1    0.776 0.02083        0.737        0.818
 1297    278       1    0.774 0.02094        0.734        0.816
 1350    266       1    0.771 0.02106        0.730        0.813
 1356    265       1    0.768 0.02118        0.727        0.810
 1360    264       1    0.765 0.02130        0.724        0.808
 1413    255       1    0.762 0.02143        0.721        0.805
 1427    251       1    0.759 0.02156        0.718        0.802
 1434    249       1    0.756 0.02168        0.714        0.799
 1444    245       1    0.753 0.02181        0.711        0.797
 1462    241       1    0.750 0.02195        0.708        0.794
 1478    240       1    0.746 0.02207        0.704        0.791
 1487    238       1    0.743 0.02220        0.701        0.788
 1492    237       1    0.740 0.02233        0.698        0.785
 1518    235       1    0.737 0.02246        0.694        0.782
 1536    233       1    0.734 0.02258        0.691        0.779
 1576    227       1    0.731 0.02271        0.687        0.777
 1616    221       1    0.727 0.02285        0.684        0.774
 1657    215       1    0.724 0.02299        0.680        0.770
 1682    211       1    0.721 0.02314        0.677        0.767
 1690    210       2    0.714 0.02342        0.669        0.761
 1741    204       1    0.710 0.02357        0.665        0.758
 1746    203       1    0.707 0.02371        0.662        0.755
 1786    196       1    0.703 0.02386        0.658        0.751
 1827    193       1    0.699 0.02401        0.654        0.748
 1847    190       1    0.696 0.02417        0.650        0.745
 1925    184       1    0.692 0.02433        0.646        0.741
 2055    171       1    0.688 0.02452        0.641        0.738
 2071    170       1    0.684 0.02471        0.637        0.734
 2081    169       1    0.680 0.02489        0.633        0.730
 2090    168       1    0.676 0.02507        0.628        0.727
 2105    166       1    0.672 0.02525        0.624        0.723
 2111    164       1    0.668 0.02542        0.620        0.719
 2224    152       1    0.663 0.02563        0.615        0.715
 2256    147       1    0.659 0.02585        0.610        0.711
 2288    144       1    0.654 0.02607        0.605        0.707
 2297    142       1    0.650 0.02629        0.600        0.703
 2386    132       1    0.645 0.02655        0.595        0.699
 2400    131       1    0.640 0.02680        0.589        0.694
 2419    129       1    0.635 0.02705        0.584        0.690
 2466    124       1    0.630 0.02731        0.578        0.685
 2503    121       1    0.624 0.02758        0.573        0.681
 2540    115       1    0.619 0.02786        0.567        0.676
 2583    106       1    0.613 0.02821        0.560        0.671
 2598    105       1    0.607 0.02854        0.554        0.666
 2689     97       1    0.601 0.02892        0.547        0.660
 2769     91       1    0.594 0.02935        0.540        0.655
 2796     89       1    0.588 0.02977        0.532        0.649
 2812     87       1    0.581 0.03018        0.525        0.643
 2847     83       1    0.574 0.03062        0.517        0.637
 3086     70       1    0.566 0.03126        0.508        0.630
 3090     69       1    0.558 0.03187        0.498        0.624
 3170     62       1    0.549 0.03260        0.488        0.616
 3222     61       1    0.540 0.03328        0.478        0.609
 3244     58       1    0.530 0.03398        0.468        0.601
 3282     56       1    0.521 0.03467        0.457        0.593
 3358     53       1    0.511 0.03538        0.446        0.585
 3395     51       1    0.501 0.03608        0.435        0.577
 3428     49       1    0.491 0.03676        0.424        0.568
 3445     48       1    0.481 0.03739        0.413        0.560
 3561     40       1    0.469 0.03834        0.399        0.550
 3574     39       1    0.456 0.03919        0.386        0.540
 3584     36       1    0.444 0.04010        0.372        0.530
 3762     32       1    0.430 0.04118        0.356        0.519
 3839     29       1    0.415 0.04234        0.340        0.507
 3853     27       1    0.400 0.04347        0.323        0.495
 4079     19       1    0.379 0.04600        0.298        0.480
 4191     15       1    0.353 0.04938        0.269        0.465</code></pre>
</div>
</div>
<p>Plot the survival probability</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(KM1, <span class="at">data =</span> data1, <span class="at">risk.table =</span> <span class="cn">TRUE</span>, <span class="at">linetype =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">pval =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in .pvalue(fit, data = data, method = method, pval = pval, pval.coord = pval.coord, : There are no survival curves to be compared. 
 This is a null model.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="cirrhosis_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="kaplan-meier-estimates-for-groups" class="level3">
<h3 class="anchored" data-anchor-id="kaplan-meier-estimates-for-groups"><strong>Kaplan-Meier estimates for groups</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>KM1.g <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(<span class="at">time =</span> data1<span class="sc">$</span>time, <span class="at">event =</span> data1<span class="sc">$</span>status_binary <span class="sc">==</span> <span class="st">"death"</span>) <span class="sc">~</span> Sex, </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">type =</span> <span class="st">"kaplan-meier"</span>, <span class="at">data =</span> data1)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(KM1.g)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(time = data1$time, event = data1$status_binary == 
    "death") ~ Sex, data = data1, type = "kaplan-meier")

                Sex=Female 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
   41    368       1    0.997 0.00271        0.992        1.000
   43    367       1    0.995 0.00383        0.987        1.000
   51    366       1    0.992 0.00469        0.983        1.000
   71    365       1    0.989 0.00541        0.979        1.000
   77    364       1    0.986 0.00603        0.975        0.998
   94    363       1    0.984 0.00660        0.971        0.997
  110    362       1    0.981 0.00712        0.967        0.995
  111    361       1    0.978 0.00760        0.963        0.993
  130    360       1    0.976 0.00805        0.960        0.991
  131    359       1    0.973 0.00848        0.956        0.990
  179    358       1    0.970 0.00888        0.953        0.988
  186    357       1    0.967 0.00926        0.949        0.986
  193    356       1    0.965 0.00962        0.946        0.984
  198    355       1    0.962 0.00997        0.943        0.982
  207    354       1    0.959 0.01031        0.939        0.980
  216    353       1    0.957 0.01063        0.936        0.978
  221    352       1    0.954 0.01094        0.933        0.975
  223    351       1    0.951 0.01124        0.929        0.973
  249    350       1    0.948 0.01154        0.926        0.971
  264    349       2    0.943 0.01209        0.920        0.967
  304    347       1    0.940 0.01236        0.916        0.965
  321    346       1    0.937 0.01262        0.913        0.963
  326    345       1    0.935 0.01287        0.910        0.960
  334    344       1    0.932 0.01312        0.907        0.958
  348    343       1    0.929 0.01336        0.904        0.956
  359    342       1    0.927 0.01359        0.900        0.954
  388    341       1    0.924 0.01382        0.897        0.951
  400    340       1    0.921 0.01405        0.894        0.949
  460    339       1    0.918 0.01426        0.891        0.947
  489    338       1    0.916 0.01448        0.888        0.945
  515    337       1    0.913 0.01469        0.885        0.942
  549    336       1    0.910 0.01489        0.882        0.940
  559    335       1    0.908 0.01510        0.878        0.938
  597    334       2    0.902 0.01549        0.872        0.933
  625    331       1    0.899 0.01568        0.869        0.931
  662    330       1    0.897 0.01587        0.866        0.928
  673    329       1    0.894 0.01605        0.863        0.926
  681    328       1    0.891 0.01623        0.860        0.924
  694    326       1    0.889 0.01641        0.857        0.921
  703    325       1    0.886 0.01658        0.854        0.919
  708    324       1    0.883 0.01676        0.851        0.917
  727    323       1    0.880 0.01693        0.848        0.914
  733    321       1    0.878 0.01710        0.845        0.912
  750    319       1    0.875 0.01726        0.842        0.909
  769    318       1    0.872 0.01743        0.839        0.907
  778    317       1    0.869 0.01759        0.836        0.905
  785    316       1    0.867 0.01774        0.832        0.902
  786    315       1    0.864 0.01790        0.829        0.900
  790    313       1    0.861 0.01805        0.826        0.897
  791    312       1    0.858 0.01821        0.823        0.895
  797    311       1    0.856 0.01836        0.820        0.892
  824    310       1    0.853 0.01850        0.817        0.890
  850    307       1    0.850 0.01865        0.814        0.887
  853    306       1    0.847 0.01879        0.811        0.885
  859    305       1    0.844 0.01894        0.808        0.882
  904    303       1    0.842 0.01908        0.805        0.880
  930    302       1    0.839 0.01922        0.802        0.877
  935    301       1    0.836 0.01935        0.799        0.875
  943    299       1    0.833 0.01949        0.796        0.872
  971    297       1    0.831 0.01963        0.793        0.870
  974    296       1    0.828 0.01976        0.790        0.867
  980    294       1    0.825 0.01989        0.787        0.865
  990    292       1    0.822 0.02002        0.784        0.862
 1000    290       1    0.819 0.02015        0.781        0.860
 1037    287       1    0.816 0.02029        0.778        0.857
 1080    282       1    0.813 0.02042        0.774        0.854
 1083    281       1    0.811 0.02055        0.771        0.852
 1095    277       1    0.808 0.02068        0.768        0.849
 1165    269       1    0.805 0.02082        0.765        0.847
 1168    268       1    0.802 0.02096        0.762        0.844
 1170    267       1    0.799 0.02110        0.758        0.841
 1191    266       2    0.793 0.02136        0.752        0.836
 1197    264       1    0.790 0.02149        0.749        0.833
 1212    263       1    0.787 0.02162        0.745        0.830
 1235    257       1    0.784 0.02175        0.742        0.827
 1350    241       1    0.780 0.02190        0.739        0.824
 1356    240       1    0.777 0.02205        0.735        0.822
 1413    231       1    0.774 0.02221        0.731        0.818
 1427    228       1    0.770 0.02237        0.728        0.815
 1434    226       1    0.767 0.02253        0.724        0.812
 1444    222       1    0.763 0.02269        0.720        0.809
 1462    218       1    0.760 0.02285        0.716        0.806
 1487    216       1    0.756 0.02302        0.713        0.803
 1492    215       1    0.753 0.02318        0.709        0.800
 1518    213       1    0.749 0.02334        0.705        0.797
 1576    206       1    0.746 0.02351        0.701        0.793
 1616    200       1    0.742 0.02368        0.697        0.790
 1657    196       1    0.738 0.02386        0.693        0.787
 1690    192       2    0.731 0.02422        0.685        0.780
 1741    186       1    0.727 0.02441        0.680        0.776
 1786    180       1    0.723 0.02461        0.676        0.772
 1827    177       1    0.718 0.02480        0.671        0.769
 1847    174       1    0.714 0.02500        0.667        0.765
 1925    169       1    0.710 0.02521        0.662        0.761
 2055    157       1    0.706 0.02545        0.657        0.757
 2071    156       1    0.701 0.02569        0.653        0.753
 2081    155       1    0.697 0.02592        0.648        0.749
 2090    154       1    0.692 0.02614        0.643        0.745
 2105    152       1    0.687 0.02636        0.638        0.741
 2111    150       1    0.683 0.02658        0.633        0.737
 2224    138       1    0.678 0.02685        0.627        0.733
 2256    134       1    0.673 0.02712        0.622        0.728
 2288    131       1    0.668 0.02739        0.616        0.724
 2297    129       1    0.663 0.02767        0.611        0.719
 2400    119       1    0.657 0.02799        0.604        0.714
 2419    117       1    0.651 0.02831        0.598        0.709
 2466    112       1    0.646 0.02864        0.592        0.704
 2503    109       1    0.640 0.02899        0.585        0.699
 2540    103       1    0.633 0.02936        0.578        0.694
 2583     94       1    0.627 0.02981        0.571        0.688
 2598     93       1    0.620 0.03025        0.563        0.682
 2769     80       1    0.612 0.03084        0.555        0.676
 2812     77       1    0.604 0.03145        0.546        0.669
 2847     74       1    0.596 0.03207        0.536        0.662
 3086     62       1    0.586 0.03296        0.525        0.655
 3090     61       1    0.577 0.03380        0.514        0.647
 3170     54       1    0.566 0.03482        0.502        0.639
 3222     53       1    0.556 0.03576        0.490        0.630
 3244     50       1    0.544 0.03673        0.477        0.621
 3282     48       1    0.533 0.03768        0.464        0.612
 3358     45       1    0.521 0.03866        0.451        0.603
 3428     42       1    0.509 0.03968        0.437        0.593
 3445     41       1    0.496 0.04060        0.423        0.583
 3561     34       1    0.482 0.04195        0.406        0.571
 3574     33       1    0.467 0.04315        0.390        0.560
 3584     30       1    0.452 0.04443        0.372        0.548
 3762     26       1    0.434 0.04599        0.353        0.534
 3839     24       1    0.416 0.04750        0.333        0.520
 3853     22       1    0.397 0.04896        0.312        0.506

                Sex=Male 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
  140     44       1    0.977  0.0225       0.9342        1.000
  191     43       1    0.955  0.0314       0.8949        1.000
  552     41       1    0.931  0.0383       0.8591        1.000
  611     40       1    0.908  0.0439       0.8260        0.998
  762     39       1    0.885  0.0485       0.7945        0.985
  799     38       1    0.861  0.0525       0.7644        0.971
  890     36       1    0.837  0.0563       0.7342        0.955
  999     35       1    0.814  0.0595       0.7049        0.939
 1012     34       1    0.790  0.0624       0.6763        0.922
 1077     33       1    0.766  0.0649       0.6485        0.904
 1152     31       1    0.741  0.0674       0.6201        0.886
 1217     29       1    0.715  0.0697       0.5911        0.866
 1297     28       1    0.690  0.0718       0.5627        0.846
 1360     25       1    0.662  0.0740       0.5320        0.824
 1478     23       1    0.634  0.0762       0.5005        0.802
 1536     22       1    0.605  0.0780       0.4697        0.779
 1682     19       1    0.573  0.0801       0.4356        0.754
 1746     18       1    0.541  0.0817       0.4024        0.727
 2386     13       1    0.499  0.0854       0.3572        0.698
 2689     12       1    0.458  0.0878       0.3143        0.667
 2796     11       1    0.416  0.0892       0.2735        0.633
 3395      8       1    0.364  0.0920       0.2220        0.597
 4079      5       1    0.291  0.0983       0.1504        0.564
 4191      4       1    0.219  0.0970       0.0915        0.522</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(KM1.g, <span class="at">data =</span> data1, <span class="at">risk.table =</span> <span class="cn">TRUE</span>, </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">linetype =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">pval =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cirrhosis_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>KM1.stage <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(<span class="at">time =</span> data1<span class="sc">$</span>time, <span class="at">event =</span> data1<span class="sc">$</span>status_binary <span class="sc">==</span> <span class="st">"death"</span>) <span class="sc">~</span> Stage, </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">type =</span> <span class="st">"kaplan-meier"</span>, <span class="at">data =</span> data1)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(KM1.stage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(time = data1$time, event = data1$status_binary == 
    "death") ~ Stage, data = data1, type = "kaplan-meier")

                Stage=1 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
  489     21       1    0.952  0.0465        0.866            1
 2386     13       1    0.879  0.0824        0.732            1

                Stage=2 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
  130     92       1    0.989  0.0108        0.968        1.000
  625     91       1    0.978  0.0152        0.949        1.000
  791     89       1    0.967  0.0186        0.932        1.000
  799     88       1    0.956  0.0214        0.915        0.999
  853     86       1    0.945  0.0238        0.900        0.993
  990     84       1    0.934  0.0261        0.884        0.986
  999     82       1    0.923  0.0281        0.869        0.979
 1168     78       1    0.911  0.0302        0.853        0.972
 1235     75       1    0.899  0.0321        0.838        0.964
 1741     64       1    0.885  0.0345        0.819        0.955
 1746     63       1    0.870  0.0367        0.801        0.946
 1847     61       1    0.856  0.0388        0.783        0.936
 2111     57       1    0.841  0.0409        0.765        0.925
 2400     47       1    0.823  0.0438        0.742        0.914
 2419     46       1    0.805  0.0464        0.719        0.902
 2583     41       1    0.786  0.0492        0.695        0.888
 2689     38       1    0.765  0.0521        0.669        0.874
 2812     34       1    0.743  0.0552        0.642        0.859
 3086     25       1    0.713  0.0605        0.604        0.842
 3222     21       1    0.679  0.0664        0.560        0.822
 3839     11       1    0.617  0.0843        0.472        0.807
 3853     10       1    0.555  0.0958        0.396        0.779
 4079      6       1    0.463  0.1163        0.283        0.757

                Stage=3 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
  140    155       1    0.994 0.00643        0.981        1.000
  198    154       1    0.987 0.00906        0.969        1.000
  249    153       1    0.981 0.01107        0.959        1.000
  326    152       1    0.974 0.01274        0.950        0.999
  515    151       1    0.968 0.01419        0.940        0.996
  597    150       1    0.961 0.01549        0.931        0.992
  611    149       1    0.955 0.01668        0.923        0.988
  662    148       1    0.948 0.01777        0.914        0.984
  681    147       1    0.942 0.01878        0.906        0.979
  733    144       1    0.935 0.01976        0.897        0.975
  859    142       1    0.929 0.02069        0.889        0.970
  943    140       1    0.922 0.02158        0.881        0.965
  974    138       1    0.915 0.02243        0.873        0.961
 1080    133       1    0.909 0.02330        0.864        0.955
 1095    130       1    0.902 0.02414        0.856        0.950
 1152    125       1    0.894 0.02500        0.847        0.945
 1170    124       1    0.887 0.02582        0.838        0.939
 1212    123       1    0.880 0.02660        0.829        0.934
 1297    118       1    0.873 0.02740        0.820        0.928
 1360    114       1    0.865 0.02821        0.811        0.922
 1413    109       1    0.857 0.02904        0.802        0.916
 1427    106       1    0.849 0.02987        0.792        0.909
 1444    104       1    0.841 0.03068        0.783        0.903
 1478    103       1    0.833 0.03145        0.773        0.897
 1487    102       1    0.824 0.03218        0.764        0.890
 1536    100       1    0.816 0.03290        0.754        0.883
 1576     95       1    0.808 0.03366        0.744        0.876
 1657     88       1    0.798 0.03450        0.734        0.869
 1690     85       1    0.789 0.03535        0.723        0.861
 1786     80       1    0.779 0.03626        0.711        0.854
 2055     64       1    0.767 0.03768        0.697        0.844
 2081     63       1    0.755 0.03900        0.682        0.835
 2090     62       1    0.743 0.04023        0.668        0.826
 2105     61       1    0.730 0.04137        0.654        0.816
 2224     54       1    0.717 0.04276        0.638        0.806
 2256     52       1    0.703 0.04410        0.622        0.795
 2288     51       1    0.689 0.04534        0.606        0.784
 2466     43       1    0.673 0.04703        0.587        0.772
 2503     42       1    0.657 0.04857        0.569        0.760
 2769     32       1    0.637 0.05121        0.544        0.745
 2847     30       1    0.615 0.05372        0.519        0.730
 3170     24       1    0.590 0.05728        0.488        0.713
 3282     21       1    0.562 0.06105        0.454        0.695
 3395     18       1    0.531 0.06515        0.417        0.675
 3428     16       1    0.497 0.06900        0.379        0.653
 3574     15       1    0.464 0.07193        0.343        0.629
 3584     12       1    0.426 0.07563        0.300        0.603
 4191      5       1    0.340 0.09724        0.194        0.596

                Stage=4 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
   41    144       1    0.993 0.00692       0.9796        1.000
   43    143       1    0.986 0.00975       0.9672        1.000
   51    142       1    0.979 0.01190       0.9561        1.000
   71    141       1    0.972 0.01369       0.9457        0.999
   77    140       1    0.965 0.01526       0.9358        0.996
   94    139       1    0.958 0.01665       0.9262        0.992
  110    138       1    0.951 0.01792       0.9169        0.987
  111    137       1    0.944 0.01909       0.9078        0.983
  131    136       1    0.938 0.02017       0.8988        0.978
  179    135       1    0.931 0.02118       0.8899        0.973
  186    134       1    0.924 0.02213       0.8812        0.968
  191    133       1    0.917 0.02303       0.8726        0.963
  193    132       1    0.910 0.02388       0.8641        0.958
  207    131       1    0.903 0.02469       0.8557        0.952
  216    130       1    0.896 0.02546       0.8473        0.947
  221    129       1    0.889 0.02619       0.8390        0.942
  223    128       1    0.882 0.02689       0.8308        0.936
  264    127       2    0.868 0.02820       0.8145        0.925
  304    125       1    0.861 0.02882       0.8064        0.919
  321    124       1    0.854 0.02941       0.7984        0.914
  334    123       1    0.847 0.02998       0.7905        0.908
  348    122       1    0.840 0.03053       0.7825        0.902
  359    121       1    0.833 0.03106       0.7746        0.896
  388    120       1    0.826 0.03156       0.7668        0.891
  400    119       1    0.819 0.03205       0.7590        0.885
  460    118       1    0.813 0.03253       0.7512        0.879
  549    116       1    0.805 0.03299       0.7434        0.873
  552    115       1    0.798 0.03344       0.7356        0.867
  559    114       1    0.791 0.03387       0.7278        0.861
  597    113       1    0.784 0.03429       0.7201        0.855
  673    111       1    0.777 0.03470       0.7123        0.848
  694    110       1    0.770 0.03510       0.7045        0.842
  703    109       1    0.763 0.03548       0.6968        0.836
  708    108       1    0.756 0.03585       0.6891        0.830
  727    107       1    0.749 0.03620       0.6814        0.824
  750    106       1    0.742 0.03654       0.6738        0.817
  762    105       1    0.735 0.03687       0.6662        0.811
  769    104       1    0.728 0.03719       0.6586        0.805
  778    103       1    0.721 0.03749       0.6510        0.798
  785    102       1    0.714 0.03779       0.6435        0.792
  786    101       1    0.707 0.03807       0.6359        0.785
  790    100       1    0.700 0.03834       0.6284        0.779
  797     99       1    0.693 0.03860       0.6209        0.773
  824     98       1    0.686 0.03884       0.6135        0.766
  850     96       1    0.678 0.03909       0.6059        0.760
  890     95       1    0.671 0.03933       0.5984        0.753
  904     93       1    0.664 0.03956       0.5909        0.746
  930     92       1    0.657 0.03978       0.5833        0.740
  935     91       1    0.650 0.04000       0.5758        0.733
  971     90       1    0.642 0.04020       0.5682        0.726
  980     88       1    0.635 0.04040       0.5606        0.719
 1000     87       1    0.628 0.04059       0.5531        0.713
 1012     86       1    0.620 0.04077       0.5455        0.706
 1037     83       1    0.613 0.04096       0.5378        0.699
 1077     82       1    0.606 0.04113       0.5301        0.692
 1083     81       1    0.598 0.04130       0.5224        0.685
 1165     77       1    0.590 0.04149       0.5143        0.677
 1191     75       2    0.575 0.04185       0.4981        0.663
 1197     73       1    0.567 0.04201       0.4901        0.655
 1217     72       1    0.559 0.04215       0.4820        0.648
 1350     62       1    0.550 0.04243       0.4726        0.640
 1356     61       1    0.541 0.04268       0.4633        0.631
 1434     57       1    0.531 0.04297       0.4534        0.623
 1462     53       1    0.521 0.04331       0.4429        0.613
 1492     52       1    0.511 0.04363       0.4325        0.604
 1518     51       1    0.501 0.04391       0.4221        0.595
 1616     48       1    0.491 0.04422       0.4113        0.586
 1682     46       1    0.480 0.04452       0.4003        0.576
 1690     45       1    0.469 0.04479       0.3894        0.566
 1827     40       1    0.458 0.04519       0.3772        0.555
 1925     38       1    0.446 0.04557       0.3647        0.545
 2071     34       1    0.433 0.04608       0.3510        0.533
 2297     30       1    0.418 0.04675       0.3359        0.521
 2540     24       1    0.401 0.04793       0.3170        0.507
 2598     19       1    0.380 0.04984       0.2935        0.491
 2796     15       1    0.354 0.05255       0.2649        0.474
 3090     12       1    0.325 0.05585       0.2319        0.455
 3244     11       1    0.295 0.05806       0.2008        0.434
 3358     10       1    0.266 0.05929       0.1716        0.411
 3445      9       1    0.236 0.05960       0.1441        0.387
 3561      7       1    0.202 0.05988       0.1134        0.361
 3762      6       1    0.169 0.05864       0.0854        0.333</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(KM1.stage, <span class="at">data =</span> data1, <span class="at">risk.table =</span> <span class="cn">TRUE</span>, </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">linetype =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="at">pval =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cirrhosis_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>comparing Kaplan Meier across groups</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(<span class="at">time =</span> data1<span class="sc">$</span>time, <span class="at">event =</span> data1<span class="sc">$</span>status_binary <span class="sc">==</span> <span class="st">"death"</span>) <span class="sc">~</span> Sex, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> data1, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">rho =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(time = data1$time, event = data1$status_binary == 
    "death") ~ Sex, data = data1, rho = 0)

             N Observed Expected (O-E)^2/E (O-E)^2/V
Sex=Female 368      133    139.9     0.339      3.13
Sex=Male    44       24     17.1     2.770      3.13

 Chisq= 3.1  on 1 degrees of freedom, p= 0.08 </code></pre>
</div>
</div>
<p>No significant difference in survival estimates between the male and female by log rank test (p=0.08)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(<span class="at">time =</span> data1<span class="sc">$</span>time, <span class="at">event =</span> data1<span class="sc">$</span>status_binary <span class="sc">==</span> <span class="st">"death"</span>) <span class="sc">~</span> Stage, </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> data1, </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">rho =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(time = data1$time, event = data1$status_binary == 
    "death") ~ Stage, data = data1, rho = 0)

          N Observed Expected (O-E)^2/E (O-E)^2/V
Stage=1  21        2     11.4      7.78      8.46
Stage=2  92       23     44.1     10.12     14.25
Stage=3 155       48     61.3      2.87      4.73
Stage=4 144       84     40.2     47.81     65.29

 Chisq= 70.1  on 3 degrees of freedom, p= 4e-15 </code></pre>
</div>
</div>
<p>There was a statistically significant difference in survival distributions between the groups of stages .</p>
</section>
<section id="kaplan-meier-cumulative-hazard-function-estimate" class="level3">
<h3 class="anchored" data-anchor-id="kaplan-meier-cumulative-hazard-function-estimate">Kaplan Meier Cumulative Hazard Function Estimate</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  KM1,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">fun =</span> <span class="st">"cumhaz"</span>,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">pval.method =</span> <span class="cn">TRUE</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.int =</span> <span class="cn">TRUE</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ggtheme =</span> <span class="fu">theme_light</span>(),</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Kaplan-Meier Cumulative Hazard Function Estimate"</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cirrhosis_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>epiR<span class="sc">::</span><span class="fu">epi.insthaz</span>(KM1) <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> hest)) <span class="sc">+</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">formula =</span> <span class="st">"y ~ x"</span>) <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Kaplan-Meier Hazard Function Estimate"</span>, </span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Time"</span>, <span class="at">y =</span> <span class="st">"Instantaneous Hazard"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cirrhosis_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="fitting-the-parametric-survival-model" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-parametric-survival-model">Fitting the Parametric Survival Model</h2>
<p>Parametric survival model able to describe the effect of multiple covariates on survival of PCB patient, assuming the survival time follows parametric distribution. Clinically significant covariates such as age, stage of cirrhosis and serum bilirubin are included to predict survival in the following parametric survival models.</p>
<section id="exponential-model" class="level3">
<h3 class="anchored" data-anchor-id="exponential-model">Exponential model</h3>
<p>In the exponential survival model, the hazard is assumed to be constant over time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>surv.mod <span class="ot">&lt;-</span> <span class="fu">Surv</span>(<span class="at">time =</span> data1<span class="sc">$</span>time, <span class="at">event =</span> data1<span class="sc">$</span>status_binary <span class="sc">==</span> <span class="st">"death"</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>exp.mod <span class="ot">&lt;-</span> <span class="fu">survreg</span>(surv.mod <span class="sc">~</span> age_years <span class="sc">+</span> Stage <span class="sc">+</span> Bilirubin, <span class="at">data =</span> data1, <span class="at">dist =</span> <span class="st">"exponential"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(exp.mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
survreg(formula = surv.mod ~ age_years + Stage + Bilirubin, data = data1, 
    dist = "exponential")
               Value Std. Error      z      p
(Intercept) 11.75605    0.80750  14.56 &lt;2e-16
age_years   -0.02884    0.00798  -3.61 0.0003
Stage2      -0.76183    0.73904  -1.03 0.3026
Stage3      -1.09182    0.72395  -1.51 0.1315
Stage4      -1.87771    0.71980  -2.61 0.0091
Bilirubin   -0.12669    0.01152 -11.00 &lt;2e-16

Scale fixed at 1 

Exponential distribution
Loglik(model)= -1420   Loglik(intercept only)= -1495.1
    Chisq= 150.37 on 5 degrees of freedom, p= 1.1e-30 
Number of Newton-Raphson Iterations: 5 
n= 412 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl_regression</span>(exp.mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `exponentiate` argument is not supported in the `tidy()` method
for `survreg` objects and will be ignored.</code></pre>
</div>
<div class="cell-output-display">

<div id="ajjfryjngl" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#ajjfryjngl table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#ajjfryjngl thead, #ajjfryjngl tbody, #ajjfryjngl tfoot, #ajjfryjngl tr, #ajjfryjngl td, #ajjfryjngl th {
  border-style: none;
}

#ajjfryjngl p {
  margin: 0;
  padding: 0;
}

#ajjfryjngl .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ajjfryjngl .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#ajjfryjngl .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ajjfryjngl .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ajjfryjngl .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ajjfryjngl .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ajjfryjngl .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ajjfryjngl .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ajjfryjngl .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ajjfryjngl .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ajjfryjngl .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ajjfryjngl .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ajjfryjngl .gt_spanner_row {
  border-bottom-style: hidden;
}

#ajjfryjngl .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#ajjfryjngl .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ajjfryjngl .gt_from_md > :first-child {
  margin-top: 0;
}

#ajjfryjngl .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ajjfryjngl .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ajjfryjngl .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ajjfryjngl .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ajjfryjngl .gt_row_group_first td {
  border-top-width: 2px;
}

#ajjfryjngl .gt_row_group_first th {
  border-top-width: 2px;
}

#ajjfryjngl .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ajjfryjngl .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ajjfryjngl .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ajjfryjngl .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ajjfryjngl .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ajjfryjngl .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ajjfryjngl .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#ajjfryjngl .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ajjfryjngl .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ajjfryjngl .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ajjfryjngl .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ajjfryjngl .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ajjfryjngl .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ajjfryjngl .gt_left {
  text-align: left;
}

#ajjfryjngl .gt_center {
  text-align: center;
}

#ajjfryjngl .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ajjfryjngl .gt_font_normal {
  font-weight: normal;
}

#ajjfryjngl .gt_font_bold {
  font-weight: bold;
}

#ajjfryjngl .gt_font_italic {
  font-style: italic;
}

#ajjfryjngl .gt_super {
  font-size: 65%;
}

#ajjfryjngl .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#ajjfryjngl .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ajjfryjngl .gt_indent_1 {
  text-indent: 5px;
}

#ajjfryjngl .gt_indent_2 {
  text-indent: 10px;
}

#ajjfryjngl .gt_indent_3 {
  text-indent: 15px;
}

#ajjfryjngl .gt_indent_4 {
  text-indent: 20px;
}

#ajjfryjngl .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="<strong>Characteristic</strong>"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>Beta</strong>"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>95% CI</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>p-value</strong>"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">age_years</td>
<td headers="estimate" class="gt_row gt_center">-0.03</td>
<td headers="ci" class="gt_row gt_center">-0.04, -0.01</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Stage</td>
<td headers="estimate" class="gt_row gt_center"><br></td>
<td headers="ci" class="gt_row gt_center"><br></td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;1</td>
<td headers="estimate" class="gt_row gt_center">—</td>
<td headers="ci" class="gt_row gt_center">—</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;2</td>
<td headers="estimate" class="gt_row gt_center">-0.76</td>
<td headers="ci" class="gt_row gt_center">-2.2, 0.69</td>
<td headers="p.value" class="gt_row gt_center">0.3</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;3</td>
<td headers="estimate" class="gt_row gt_center">-1.1</td>
<td headers="ci" class="gt_row gt_center">-2.5, 0.33</td>
<td headers="p.value" class="gt_row gt_center">0.13</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;4</td>
<td headers="estimate" class="gt_row gt_center">-1.9</td>
<td headers="ci" class="gt_row gt_center">-3.3, -0.47</td>
<td headers="p.value" class="gt_row gt_center">0.009</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Bilirubin</td>
<td headers="estimate" class="gt_row gt_center">-0.13</td>
<td headers="ci" class="gt_row gt_center">-0.15, -0.10</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> CI = Confidence Interval</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
</div>
<p>Interpretation</p>
<p>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Age</p>
<ul>
<li><p>The estimated log time ratio to die for every increment of 1 year of age is -0.03. The Acceleration Factor (AF) or Time Ratio (TR) is 𝑒<sup>−0.03</sup>=0.972. This indicate with the addition of each year, the time to death is accelerated by a factor of 0.972.</p></li>
<li><p>The estimated hazard ratio (HR) with addition of one year is e<sup>0.03</sup>=1.029, which means the risk of death is significantly higher by 2.9% with the increase of one year of age when adjusted for the stage of cirrhosis and serum bilirubin.</p></li>
</ul>
<p>2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; stage</p>
<ul>
<li><p>The estimated log time ratio to die in PCB patient in stage 4 in comparison to stage 1 is -1.878. The Acceleration Factor (AF) or Time Ratio (TR) is 𝑒<sup>−1.878</sup>=0.153, meaning being in Stage 4 accelerates the time to death by a factor of 0.153 compared to Stage 1.</p></li>
<li><p>The estimated hazard ratio (HR) comparing Stage 4 to Stage 1 is e<sup>1.878</sup>=6.538, which means patient in Stage 4 have 6.5 times higher risk of death compared to those in Stage 1 when adjusted for the age and serum bilirubin.</p></li>
</ul>
<p>3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Bilirubin</p>
<ul>
<li><p>The estimated log time ratio to die for every increment of 1mg/dl of serum bilirubin is -0.127 The Acceleration Factor (AF) or Time Ratio (TR) is 𝑒<sup>−0.127</sup>=0.881. This indicate with 1mg/dl increase in serum bilirubin, the time to death is accelerated by a factor of 0.881.</p></li>
<li><p>The estimated hazard ratio (HR) comparing the increase of 1mg/dl of serum bilirubin is e<sup>0.127</sup>=1.135, which means the risk of death is higher by 13.5% with each 1mg/dl increase in serum bilirubin when adjusted for the stage of cirrhosis and age.</p></li>
</ul>
</section>
<section id="weibull-model" class="level3">
<h3 class="anchored" data-anchor-id="weibull-model">Weibull model</h3>
<section id="accelerated-failure-time-atf-model" class="level4">
<h4 class="anchored" data-anchor-id="accelerated-failure-time-atf-model">Accelerated Failure Time (ATF) model</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>wei.mod.aft <span class="ot">&lt;-</span> <span class="fu">flexsurvreg</span>(surv.mod <span class="sc">~</span> age_years <span class="sc">+</span> Stage <span class="sc">+</span> Bilirubin , <span class="at">data =</span> data1, <span class="at">dist =</span> <span class="st">'weibull'</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>wei.mod.aft</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
flexsurvreg(formula = surv.mod ~ age_years + Stage + Bilirubin, 
    data = data1, dist = "weibull")

Estimates: 
           data mean  est        L95%       U95%       se         exp(est) 
shape             NA   1.37e+00   1.21e+00   1.56e+00   9.03e-02         NA
scale             NA   4.73e+04   1.42e+04   1.57e+05   2.90e+04         NA
age_years   5.06e+01  -2.16e-02  -3.31e-02  -1.00e-02   5.88e-03   9.79e-01
Stage2      2.23e-01  -5.52e-01  -1.61e+00   5.05e-01   5.39e-01   5.76e-01
Stage3      3.76e-01  -8.27e-01  -1.86e+00   2.11e-01   5.29e-01   4.37e-01
Stage4      3.50e-01  -1.46e+00  -2.50e+00  -4.19e-01   5.30e-01   2.33e-01
Bilirubin   3.23e+00  -1.05e-01  -1.23e-01  -8.73e-02   9.18e-03   9.00e-01
           L95%       U95%     
shape             NA         NA
scale             NA         NA
age_years   9.67e-01   9.90e-01
Stage2      2.00e-01   1.66e+00
Stage3      1.55e-01   1.23e+00
Stage4      8.25e-02   6.58e-01
Bilirubin   8.84e-01   9.16e-01

N = 412,  Events: 157,  Censored: 255
Total time at risk: 789737
Log-likelihood = -1409.88, df = 7
AIC = 2833.759</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl_regression</span>(wei.mod.aft)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>✖ Unable to identify the list of variables.

This is usually due to an error calling `stats::model.frame(x)`or `stats::model.matrix(x)`.
It could be the case if that type of model does not implement these methods.
Rarely, this error may occur if the model object was created within
a functional programming framework (e.g. using `lappy()`, `purrr::map()`, etc.).</code></pre>
</div>
<div class="cell-output-display">

<div id="vxknyvfogl" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#vxknyvfogl table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#vxknyvfogl thead, #vxknyvfogl tbody, #vxknyvfogl tfoot, #vxknyvfogl tr, #vxknyvfogl td, #vxknyvfogl th {
  border-style: none;
}

#vxknyvfogl p {
  margin: 0;
  padding: 0;
}

#vxknyvfogl .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#vxknyvfogl .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#vxknyvfogl .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#vxknyvfogl .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#vxknyvfogl .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#vxknyvfogl .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vxknyvfogl .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#vxknyvfogl .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#vxknyvfogl .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#vxknyvfogl .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#vxknyvfogl .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#vxknyvfogl .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#vxknyvfogl .gt_spanner_row {
  border-bottom-style: hidden;
}

#vxknyvfogl .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#vxknyvfogl .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#vxknyvfogl .gt_from_md > :first-child {
  margin-top: 0;
}

#vxknyvfogl .gt_from_md > :last-child {
  margin-bottom: 0;
}

#vxknyvfogl .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#vxknyvfogl .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#vxknyvfogl .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#vxknyvfogl .gt_row_group_first td {
  border-top-width: 2px;
}

#vxknyvfogl .gt_row_group_first th {
  border-top-width: 2px;
}

#vxknyvfogl .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#vxknyvfogl .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#vxknyvfogl .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#vxknyvfogl .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vxknyvfogl .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#vxknyvfogl .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#vxknyvfogl .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#vxknyvfogl .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#vxknyvfogl .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vxknyvfogl .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#vxknyvfogl .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#vxknyvfogl .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#vxknyvfogl .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#vxknyvfogl .gt_left {
  text-align: left;
}

#vxknyvfogl .gt_center {
  text-align: center;
}

#vxknyvfogl .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#vxknyvfogl .gt_font_normal {
  font-weight: normal;
}

#vxknyvfogl .gt_font_bold {
  font-weight: bold;
}

#vxknyvfogl .gt_font_italic {
  font-style: italic;
}

#vxknyvfogl .gt_super {
  font-size: 65%;
}

#vxknyvfogl .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#vxknyvfogl .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#vxknyvfogl .gt_indent_1 {
  text-indent: 5px;
}

#vxknyvfogl .gt_indent_2 {
  text-indent: 10px;
}

#vxknyvfogl .gt_indent_3 {
  text-indent: 15px;
}

#vxknyvfogl .gt_indent_4 {
  text-indent: 20px;
}

#vxknyvfogl .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="<strong>Characteristic</strong>"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>Beta</strong>"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>95% CI</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>p-value</strong>"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">shape</td>
<td headers="estimate" class="gt_row gt_center">1.4</td>
<td headers="ci" class="gt_row gt_center">1.2, 1.6</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">scale</td>
<td headers="estimate" class="gt_row gt_center">47,294</td>
<td headers="ci" class="gt_row gt_center">14,225, 157,240</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">age_years</td>
<td headers="estimate" class="gt_row gt_center">-0.02</td>
<td headers="ci" class="gt_row gt_center">-0.03, -0.01</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Stage2</td>
<td headers="estimate" class="gt_row gt_center">-0.55</td>
<td headers="ci" class="gt_row gt_center">-1.6, 0.51</td>
<td headers="p.value" class="gt_row gt_center">0.3</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Stage3</td>
<td headers="estimate" class="gt_row gt_center">-0.83</td>
<td headers="ci" class="gt_row gt_center">-1.9, 0.21</td>
<td headers="p.value" class="gt_row gt_center">0.12</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Stage4</td>
<td headers="estimate" class="gt_row gt_center">-1.5</td>
<td headers="ci" class="gt_row gt_center">-2.5, -0.42</td>
<td headers="p.value" class="gt_row gt_center">0.006</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Bilirubin</td>
<td headers="estimate" class="gt_row gt_center">-0.11</td>
<td headers="ci" class="gt_row gt_center">-0.12, -0.09</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> CI = Confidence Interval</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
</div>
<p>The weibull scale parameter is 0.728 and the shape parameter is 1/0.728 = 1.37.</p>
<p>Interpretation</p>
<p>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Age</p>
<ul>
<li><p>The estimated log time to death wtih the increase in one year of age was -0.022</p></li>
<li><p>The Acceleration Factor (AF) or Time Ratio (TR) is 𝑒<sup>−0.022</sup>=0.979. This indicate with the addition of each year, the time to death is accelerated by a factor of 0.979. in other words, the older individual has shorter time (by a factor of 0.979) to death when adjusted for the serum bilirubin and stage of cirrhosis.</p></li>
<li><p>The reduction in survival in PCB patients could range between 1% to 3.3% (adj.TR= 0.979, 95% CI= 0.967, 0.990)</p></li>
</ul>
<p>2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; stage</p>
<ul>
<li>The estimated log time to death for PCB patient in stage 4 in comparison to Stage 1 was -1.457.</li>
<li>The Acceleration Factor (AF) or Time Ratio (TR) is 𝑒<sup>−1.457</sup>=0.233, meaning being in Stage 4 accelerates the time to death by a factor of 0.233 compared to Stage 1 when adjusted for the serum bilirubin and age.</li>
<li>The survival in PCB patients shortened between 34.2% to 91.7% (adj.TR= 0.233, 95% CI= 0.083, 0.658)</li>
</ul>
<p>3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Bilirubin</p>
<ul>
<li>The estimated log time to death wtih the increase 1mg/dl of serum bilirubin was -0.105</li>
<li>The Acceleration Factor (AF) or Time Ratio (TR) is 𝑒<sup>−0.105</sup>=0.900. This indicate with 1mg/dl increase in serum bilirubin, the time to death is accelerated by a factor of 0.9. Higher serum bilirubin level are associated with shorter survival time by a factor of 0.9 when adjusted for the stage of cirrhosis and age.</li>
<li>The reduction in survival in PCB patients could range between 8.4% to 11.6% (adj.TR= 0.900, 95% CI= 0.884, 0.916)</li>
</ul>
</section>
<section id="proportional-hazard-ph-model" class="level4">
<h4 class="anchored" data-anchor-id="proportional-hazard-ph-model">Proportional Hazard (PH) model</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>wei.mod.ph <span class="ot">&lt;-</span> <span class="fu">flexsurvreg</span>(surv.mod <span class="sc">~</span> age_years <span class="sc">+</span> Stage <span class="sc">+</span> Bilirubin, <span class="at">data =</span> data1, <span class="at">dist =</span> <span class="st">"weibullPH"</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>wei.mod.ph</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
flexsurvreg(formula = surv.mod ~ age_years + Stage + Bilirubin, 
    data = data1, dist = "weibullPH")

Estimates: 
           data mean  est        L95%       U95%       se         exp(est) 
shape             NA   1.37e+00   1.21e+00   1.56e+00   9.03e-02         NA
scale             NA   3.80e-07   4.48e-08   3.21e-06   4.14e-07         NA
age_years   5.06e+01   2.96e-02   1.41e-02   4.51e-02   7.89e-03   1.03e+00
Stage2      2.23e-01   7.59e-01  -6.90e-01   2.21e+00   7.39e-01   2.14e+00
Stage3      3.76e-01   1.14e+00  -2.84e-01   2.56e+00   7.24e-01   3.11e+00
Stage4      3.50e-01   2.00e+00   5.90e-01   3.41e+00   7.20e-01   7.40e+00
Bilirubin   3.23e+00   1.45e-01   1.21e-01   1.68e-01   1.22e-02   1.16e+00
           L95%       U95%     
shape             NA         NA
scale             NA         NA
age_years   1.01e+00   1.05e+00
Stage2      5.01e-01   9.09e+00
Stage3      7.53e-01   1.29e+01
Stage4      1.80e+00   3.04e+01
Bilirubin   1.13e+00   1.18e+00

N = 412,  Events: 157,  Censored: 255
Total time at risk: 789737
Log-likelihood = -1409.88, df = 7
AIC = 2833.759</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl_regression</span>(wei.mod.ph)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>✖ Unable to identify the list of variables.

This is usually due to an error calling `stats::model.frame(x)`or `stats::model.matrix(x)`.
It could be the case if that type of model does not implement these methods.
Rarely, this error may occur if the model object was created within
a functional programming framework (e.g. using `lappy()`, `purrr::map()`, etc.).</code></pre>
</div>
<div class="cell-output-display">

<div id="efdsdiezow" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#efdsdiezow table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#efdsdiezow thead, #efdsdiezow tbody, #efdsdiezow tfoot, #efdsdiezow tr, #efdsdiezow td, #efdsdiezow th {
  border-style: none;
}

#efdsdiezow p {
  margin: 0;
  padding: 0;
}

#efdsdiezow .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#efdsdiezow .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#efdsdiezow .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#efdsdiezow .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#efdsdiezow .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#efdsdiezow .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#efdsdiezow .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#efdsdiezow .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#efdsdiezow .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#efdsdiezow .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#efdsdiezow .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#efdsdiezow .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#efdsdiezow .gt_spanner_row {
  border-bottom-style: hidden;
}

#efdsdiezow .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#efdsdiezow .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#efdsdiezow .gt_from_md > :first-child {
  margin-top: 0;
}

#efdsdiezow .gt_from_md > :last-child {
  margin-bottom: 0;
}

#efdsdiezow .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#efdsdiezow .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#efdsdiezow .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#efdsdiezow .gt_row_group_first td {
  border-top-width: 2px;
}

#efdsdiezow .gt_row_group_first th {
  border-top-width: 2px;
}

#efdsdiezow .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#efdsdiezow .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#efdsdiezow .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#efdsdiezow .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#efdsdiezow .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#efdsdiezow .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#efdsdiezow .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#efdsdiezow .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#efdsdiezow .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#efdsdiezow .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#efdsdiezow .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#efdsdiezow .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#efdsdiezow .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#efdsdiezow .gt_left {
  text-align: left;
}

#efdsdiezow .gt_center {
  text-align: center;
}

#efdsdiezow .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#efdsdiezow .gt_font_normal {
  font-weight: normal;
}

#efdsdiezow .gt_font_bold {
  font-weight: bold;
}

#efdsdiezow .gt_font_italic {
  font-style: italic;
}

#efdsdiezow .gt_super {
  font-size: 65%;
}

#efdsdiezow .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#efdsdiezow .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#efdsdiezow .gt_indent_1 {
  text-indent: 5px;
}

#efdsdiezow .gt_indent_2 {
  text-indent: 10px;
}

#efdsdiezow .gt_indent_3 {
  text-indent: 15px;
}

#efdsdiezow .gt_indent_4 {
  text-indent: 20px;
}

#efdsdiezow .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="<strong>Characteristic</strong>"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>Beta</strong>"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>95% CI</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>p-value</strong>"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">shape</td>
<td headers="estimate" class="gt_row gt_center">1.4</td>
<td headers="ci" class="gt_row gt_center">1.2, 1.6</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">scale</td>
<td headers="estimate" class="gt_row gt_center">0.00</td>
<td headers="ci" class="gt_row gt_center">0.00, 0.00</td>
<td headers="p.value" class="gt_row gt_center"><br></td></tr>
    <tr><td headers="label" class="gt_row gt_left">age_years</td>
<td headers="estimate" class="gt_row gt_center">0.03</td>
<td headers="ci" class="gt_row gt_center">0.01, 0.05</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Stage2</td>
<td headers="estimate" class="gt_row gt_center">0.76</td>
<td headers="ci" class="gt_row gt_center">-0.69, 2.2</td>
<td headers="p.value" class="gt_row gt_center">0.3</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Stage3</td>
<td headers="estimate" class="gt_row gt_center">1.1</td>
<td headers="ci" class="gt_row gt_center">-0.28, 2.6</td>
<td headers="p.value" class="gt_row gt_center">0.12</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Stage4</td>
<td headers="estimate" class="gt_row gt_center">2.0</td>
<td headers="ci" class="gt_row gt_center">0.59, 3.4</td>
<td headers="p.value" class="gt_row gt_center">0.005</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Bilirubin</td>
<td headers="estimate" class="gt_row gt_center">0.14</td>
<td headers="ci" class="gt_row gt_center">0.12, 0.17</td>
<td headers="p.value" class="gt_row gt_center">&lt;0.001</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> CI = Confidence Interval</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
</div>
<p>Interpretation</p>
<p>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Age</p>
<ul>
<li>The estimated hazard ratio (HR) with addition of one year is e<sup>0.030</sup>=1.03, which means the risk of death is higher by 3% with the increase of one year of age when adjusted for the serum bilirubin and stage of cirrhosis.</li>
<li>The risk of death in PCB patients could increase by the range between 1% to 5% (adj.TR= 1.03, 95% CI= 1.01, 1.05 )</li>
</ul>
<p>2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; stage</p>
<ul>
<li>The estimated hazard ratio (HR) comparing Stage 4 to Stage 1 is e<sup>2.00</sup>=7.40, which means patient in Stage 4 have 7.4 times higher risk of death compared to those in Stage 1 when adjusted for the serum bilirubin and age.</li>
</ul>
<p>3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Bilirubin</p>
<ul>
<li>The estimated hazard ratio (HR) comparing the increase of 1mg/dl of serum bilirubin is e<sup>0.145</sup>=1.16 which means the risk of death is higher by 16% with each 1mg/dl increase in serum bilirubin when adjusted for the stage of cirrhosis and age.</li>
<li>the risk of death increases ranging 13% to 18% (adj.TR= 1.16, 95% CI= 1.13, 1.18 )</li>
</ul>
</section>
</section>
</section>
<section id="model-adequacy-for-weibull-distribution" class="level2">
<h2 class="anchored" data-anchor-id="model-adequacy-for-weibull-distribution"><strong>Model adequacy for Weibull distribution</strong></h2>
<p><strong>Weibull regression diagnostic plot by Stage</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(SurvRegCensCov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'SurvRegCensCov':
  method    from 
  print.src dplyr</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>diagnostic_plot <span class="ot">&lt;-</span> <span class="fu">WeibullDiag</span>(<span class="fu">Surv</span>(<span class="at">time =</span> data1<span class="sc">$</span>time, <span class="at">event =</span> data1<span class="sc">$</span>status_binary <span class="sc">==</span> <span class="st">"death"</span>) <span class="sc">~</span> Stage, <span class="at">data =</span> data1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cirrhosis_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Weibull regression diagnostic plot by sex</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>diagnostic_plot <span class="ot">&lt;-</span> <span class="fu">WeibullDiag</span>(<span class="fu">Surv</span>(<span class="at">time =</span> data1<span class="sc">$</span>time, <span class="at">event =</span> data1<span class="sc">$</span>status_binary <span class="sc">==</span> <span class="st">"death"</span>) <span class="sc">~</span> Sex, <span class="at">data =</span> data1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cirrhosis_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Weibull model is fit, the groups’ lines are parallel and linear (not flat).</p>
</section>
<section id="checking-the-ph-assumption" class="level2">
<h2 class="anchored" data-anchor-id="checking-the-ph-assumption">Checking the PH assumption</h2>
<p>Plot of log-odds of survival against the log of survival time by sex</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>kmfit <span class="ot">&lt;-</span> <span class="fu">survfit</span>(surv.mod <span class="sc">~</span> data1<span class="sc">$</span>Stage)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(kmfit<span class="sc">$</span>time), <span class="fu">log</span>(kmfit<span class="sc">$</span>surv<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>kmfit<span class="sc">$</span>surv)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cirrhosis_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot of log-odds of survival against the log of survival time by sex</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>kmfit1 <span class="ot">&lt;-</span> <span class="fu">survfit</span>(surv.mod <span class="sc">~</span> data1<span class="sc">$</span>Sex)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(kmfit1<span class="sc">$</span>time), <span class="fu">log</span>(kmfit1<span class="sc">$</span>surv<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>kmfit1<span class="sc">$</span>surv)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cirrhosis_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The plots do not look like a straight lines. It is also not parallel. So it does not support PH assumption. Our&nbsp;<strong>PH asssumption is violated</strong>.</p>
</section>
<section id="comparing-models" class="level2">
<h2 class="anchored" data-anchor-id="comparing-models">Comparing models</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>exp.mod_AIC <span class="ot">&lt;-</span> <span class="fu">AIC</span>(exp.mod)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>wei.mod.aft_AIC <span class="ot">&lt;-</span> wei.mod.aft<span class="sc">$</span>AIC</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>wei.mod.ph_AIC <span class="ot">&lt;-</span> wei.mod.ph<span class="sc">$</span>AIC</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>aic_values <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">c</span>(<span class="st">"Weibull AFT"</span>, <span class="st">"Weibull PH"</span>, <span class="st">"Exponential"</span>),</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">AIC =</span> <span class="fu">c</span>(wei.mod.aft_AIC, wei.mod.ph_AIC, exp.mod_AIC)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(aic_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Model      AIC
1 Weibull AFT 2833.759
2  Weibull PH 2833.759
3 Exponential 2851.916</code></pre>
</div>
</div>
<p>Weibull model is a better fit model compared to exponential model as it has lower AIC.</p>
</section>
<section id="plot-survival-probability" class="level2">
<h2 class="anchored" data-anchor-id="plot-survival-probability">Plot Survival Probability</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>weib.cirr <span class="ot">&lt;-</span> <span class="fu">survreg</span>(<span class="fu">Surv</span>(time, status_binary <span class="sc">==</span> <span class="st">"death"</span>) <span class="sc">~</span> Bilirubin, <span class="at">data =</span> data1, <span class="at">dist =</span> <span class="st">'weibull'</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(weib.cirr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
survreg(formula = Surv(time, status_binary == "death") ~ Bilirubin, 
    data = data1, dist = "weibull")
               Value Std. Error      z       p
(Intercept)  8.72678    0.09750  89.50 &lt; 2e-16
Bilirubin   -0.11119    0.00955 -11.65 &lt; 2e-16
Log(scale)  -0.24116    0.06840  -3.53 0.00042

Scale= 0.786 

Weibull distribution
Loglik(model)= -1445.9   Loglik(intercept only)= -1494.4
    Chisq= 96.92 on 1 degrees of freedom, p= 7.2e-23 
Number of Newton-Raphson Iterations: 7 
n= 412 </code></pre>
</div>
</div>
<p>Weibull survival curve for a cirrhosis subject with bilirubin of 8mg/dl</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>pct <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">98</span><span class="sc">/</span><span class="dv">100</span> <span class="co"># The 100th percentile of predicted survival is at +infinity</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>ptime <span class="ot">&lt;-</span> <span class="fu">predict</span>(weib.cirr, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">Bilirubin =</span> <span class="dv">8</span>) ,</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="at">type =</span> <span class="st">'quantile'</span>, <span class="at">p =</span> pct, <span class="at">se =</span> <span class="cn">TRUE</span>)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="fu">matplot</span>(<span class="fu">cbind</span>(ptime<span class="sc">$</span>fit, ptime<span class="sc">$</span>fit <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>ptime<span class="sc">$</span>se.fit,</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>ptime<span class="sc">$</span>fit <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span>ptime<span class="sc">$</span>se.fit)<span class="sc">/</span><span class="fl">30.5</span>, <span class="dv">1</span><span class="sc">-</span>pct,</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="at">xlab =</span> <span class="st">"Days"</span>, <span class="at">ylab =</span> <span class="st">"Survival"</span>, <span class="at">type =</span> <span class="st">'l'</span>, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>), <span class="at">col =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cirrhosis_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="prepared-by" class="level1">
<h1><strong>Prepared By</strong></h1>
<p>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Tiong Wen Ning 22307078</p>
<p>2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Hazlienor Binti Mohd Hatta 22307055</p>
<p>3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Amalina Binti Asmail @ Ismail &nbsp; 22307044</p>
<p>4.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Mohamad Afiq Amsyar Bin Hamedin 23100003</p>
<p>5.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Muhammad Saufi bin Abdullah&nbsp; 22307048</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>